### PR TITLE
Reuse compliance

### PR DESCRIPTION
**Pull request by sommerluk**
Hello.

The ICC profiles are great work!

I'm now using them in a project also for unit testing, and because this project will follow the [Reuse](https://reuse.software/) specification, I've made a [Reuse](https://reuse.software/)-compliant version of your  repository content to be able to include it. Maybe this might be an option also for upstream?

Note: I'm not sure if removing the file “license” will prevent Github from recognizing this project as CC0?

### CODE REVIEW

**Comment by saucecontrol** [comment]
Howdy, and thanks for the kind words!

I like the general idea behind Reuse, but the standard seems unnecessarily intrusive for repos where all the files fall under the same license.  After all, if GitHub is able to correctly identify the license, it's already in a machine-readable state.  I would, of course, like these profiles to be available to projects to use with minimal friction, but I'm not sold on Reuse as a way to achieve that.  Do you have examples of popular projects that have adopted it?

In any case, the contact email you've listed in the license files is the commercial support contact for the PhotoSauce project.  It doesn't belong here and most definitely doesn't belong in any third-party software.

**Comment by saucecontrol** [comment]
I'm actually not keen on attaching an 'official' copyright notice here in general, given that my intent was to release the profiles to the public domain to avoid any such requirement.  It seems the accepted standard for public domain files when following Reuse's strict requirement for a copyright notice is to simply use [`SPDX-FileCopyrightText: none`](https://community.kde.org/Guidelines_and_HOWTOs/Licensing#Which_copyright_holder_shall_I_add_to_a_CC0-1.0_file.3F), which makes more sense to me.

Giving the Reuse spec another look, I see that although the license-per-file approach for non-text files is preferred, they also support use of a DEB5 file to cover all files in a folder.  If I were to adopt changes here to support Reuse, I think that would be my preference.

What's not clear to me is whether that's appropriate for the source repo itself.  The language used in DEP5 sounds more like it would be included in a downstream repo to refer back to this one.  Is it customary to include a self-referencing DEP5 in a source repo?

**Comment by sommerluk** [comment]
> I like the general idea behind Reuse, but the standard seems unnecessarily intrusive for repos where all the files fall under the same license

Indeed, it does not look nice to add to 43 ICC profiles 43 license files.

> Do you have examples of popular projects that have adopted it?

Yes. KDE. Indeed, this is the reason for this PR. I am incubating a project that might become part of KDE ([libperceptualcolor](https://github.com/sommerluk/perceptualcolor)) and therefore I try to follow [KDE's license policy](https://community.kde.org/Guidelines_and_HOWTOs/Licensing#Which_copyright_holder_shall_I_add_to_a_CC0-1.0_file.3F) now.

> I'm actually not keen on attaching an 'official' copyright notice here in general, given that my intent was to release the profiles to the public domain to avoid any such requirement.

CC0 has in its third paragraph a “Public License Fallback”: In legislations that to not allow public domain, it gives an unlimited license. So I think it can be useful to have a copyright notice.

> also support use of a DEB5 file to cover all files in a folder

> What's not clear to me is whether that's appropriate for the source repo itself.

I'm also unsure here.

> the contact email you've listed […] doesn't belong here and most definitely doesn't belong in any third-party software.

I'm sorry about that. I'll close this PR and will delete the branch. Downstream, could I use
```
SPDX-FileCopyrightText: 2021 Clinton Ingram
SPDX-License-Identifier: CC0-1.0
```
without any e-mail?

**Comment by saucecontrol** [comment]
Interesting.  The reference I linked above is from KDE's licensing guidelines.  I can't speak to the legality of the forfeiture of copyright claims in all jurisdictions, but it at least appears to be ok with KDE to list `none` as the copyright. https://community.kde.org/Guidelines_and_HOWTOs/Licensing#Which_copyright_holder_shall_I_add_to_a_CC0-1.0_file.3F

It's not that I object to having my name attached to my work; it's more that I don't want to give anyone downstream the impression that there is any burden to preserve that information.  The DEB5 allowance in the Reuse spec is kind of the best of both worlds since it would allow a link back to the source repo while making the lack of copyright clear.

At the end of the day, though, the purpose of the CC0 license is to ensure you don't have to ask my permission for anything you do with this, so whatever you think is best is fine with me.  Thanks for the heads-up anyway.  I've learned a few things today :)

**Pull request closed without merging**
